#########################
# Project configuration #
#########################

language: cpp
dist: xenial
sudo: required

################
# Build matrix #
################

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - CMAKE_OPTIONS=-DDEBUG=ON -DBITS=64
    - os: linux
      compiler: gcc
      before_script:
        # install latest LCOV (1.9 was failing for me) [1]
        - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
        - tar xf lcov_1.11.orig.tar.gz
        - sudo make -C lcov-1.11/ install
        # install lcov to coveralls conversion + upload tool
        - gem install coveralls-lcov
        - cd ${TRAVIS_BUILD_DIR}
        # init coverage to 0 (optional)
        - lcov --directory . --zerocounters
      after_success:
        - cd ${TRAVIS_BUILD_DIR}
        - tree build
        - lcov --directory . --capture --output-file coverage.info # capture coverage info
        - lcov --remove coverage.info 'test/*' '/usr/*' 'third_parties/*' --output-file coverage.info # filter out system and test code
        - lcov --list coverage.info # debug before upload
        - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
      env:
        - CMAKE_OPTIONS=-DDEBUG=ON -DBITS=64 -DCOVERAGE=ON

install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo add-apt-repository --yes ppa:jonathonf/gcc-7.2
  - sudo apt-get update
  - scripts/install.sh tools
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - scripts/install.sh wii

script:
  # Show OS/compiler version
  - uname -a
  - $CXX --version

  - cd ${TRAVIS_BUILD_DIR}
  - rm -rf build
  - cmake -H. -Bbuild ${CMAKE_OPTIONS}
  - cd build
  - make all -j $(nproc)
  - test/unit_testing_all '[integration]'

notifications:
  email: false
